### PR TITLE
Use new confirmations endpoints

### PR DESCRIPTION
**Pull request by Lyrapuff**
Apparently Steam changed how we get confirmations, this pr should make it work again, I made a few tests and it appears to be working fine, but feel free to test it yourself to make sure

### CODE REVIEW

**Comment by lorppijw** [comment]
Hi, thanks for updating the endpoints. I still keep having this problem where this:
string response = SteamWeb.Request(APIEndpoints.COMMUNITY_BASE + "/steamguard/phoneajax", "POST", postData, _cookies);
returns a steam html page instead of a json response when I try to setup a new account.

Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: <. Path '', line 0, position 0.'

Thanks in advance

**Comment by dyc3** [comment]
That is unrelated to this PR.

**Comment by sy1989** [comment]
I think that return Array.Empty<Confirmation> when success==false or NeedAuthentication ==true is not a good idea.
You should throw new WGTokenInvalidException when success==false or NeedAuthentication ==true.
But i think return ConfirmationsResponse is better

**Comment by fjch1997** [comment]
I did some testing and it seems like `Confirmation.ConfType` is always MarketSellTransaction, when they are a trade offer.
Fiddler shows the JSON contains 
````
{
  "success": true,
  "conf": [
    {
      "type": 2,
      "type_name": "Trade Offer",
    }
  ]
}
````
The `ConfirmationType` enum type has `MarketSellTransaction = 2` which is incorrect.

I suppose that the enum definition needs to be updated.

**Comment by jorgermduarte** [comment]
great work 👍🏼

**Comment by jorgermduarte** [comment]
I used your solution and i did a temp fix for the Steam Desktop authenticator :)  🕺🏼 
Basically right now i used a HttpClient instead of the browser.

I didn't commit the files from the SteamAuth repo, since im using your solution, only added more fields to the Confirmation class:

``` 
        [JsonProperty(PropertyName = "headline")]
        public string Headline { get; set; }

        [JsonProperty(PropertyName = "summary")]
        public List<String> Summary { get; set; }

        [JsonProperty(PropertyName = "accept")]
        public string Accept { get; set; }

        [JsonProperty(PropertyName = "cancel")]
        public string Cancel { get; set; }

        [JsonProperty(PropertyName = "icon")]
        public string Icon { get; set; }

```

https://github.com/Jessecar96/SteamDesktopAuthenticator/commit/9b03d0928d100284896e4e416b2f177d4ec8b955

**Comment by jorgermduarte** [comment]
Here's my changed on the SteamAuth project:

https://github.com/geel9/SteamAuth/commit/1dd1bae576bfc9d3ca24f2093df7426c405b2e41

**Pull request merged**
